# Generated by Selenium IDE
import pytest
import time
import json
import unittest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestLoginTestSuite(unittest.TestCase):
  @classmethod
  def setUpClass(self):
    self.driver = webdriver.Firefox()
    self.driver.implicitly_wait(10)
    self.driver.maximize_window()

  @classmethod
  def tearDownClass(self):
    self.driver.close()


  def test_invalidPassword(self):
    self.driver.get("http://127.0.0.1:8000/admin/login/?next=/admin/")
    self.driver.set_window_size(1366, 713)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("rohan")
    self.driver.find_element(By.ID, "id_password").send_keys("456842135461")
    self.driver.find_element(By.CSS_SELECTOR, ".submit-row > input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".login").click()
     
  
  def test_invalidUsername(self):
    self.driver.get("http://127.0.0.1:8000/admin/login/?next=/admin/")
    self.driver.set_window_size(1366, 713)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("rohannotvalid")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("123456789")
    self.driver.find_element(By.CSS_SELECTOR, ".submit-row > input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".login").click()
     
  
  def test_onlyPassword(self):
    self.driver.get("http://127.0.0.1:8000/admin/login/?next=/admin/")
    self.driver.set_window_size(1366, 713)
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("123456489413")
    self.driver.find_element(By.CSS_SELECTOR, ".submit-row > input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".login").click()
     
  
  def test_onlyUsername(self):
    self.driver.get("http://127.0.0.1:8000/admin/login/?next=/admin/")
    self.driver.set_window_size(1366, 713)
    self.driver.find_element(By.ID, "id_username").send_keys("rohan")
    self.driver.find_element(By.CSS_SELECTOR, ".submit-row > input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".login").click()
     
  
  def test_validLogin(self):
    self.driver.get("http://127.0.0.1:8000/admin/login/?next=/admin/")
    self.driver.set_window_size(1366, 713)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("rohan")
    self.driver.find_element(By.ID, "id_password").send_keys("123456789")
    self.driver.find_element(By.CSS_SELECTOR, ".submit-row > input").click()
    self.driver.find_element_by_link_text('LOG OUT').click()
    self.driver.find_element(By.ID, "container").click()
     
  
  def test_emptyLogin(self):
    self.driver.get("http://127.0.0.1:8000/admin/login/?next=/admin/")
    self.driver.set_window_size(1366, 713)
    self.driver.find_element(By.CSS_SELECTOR, ".submit-row > input").click()
    

  

if __name__ == '__main__':
  unittest.main()