# Generated by Selenium IDE
import pytest
import time
import json
import unittest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestPollingTestSuite(unittest.TestCase):
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities={ 'browserName' : 'firefox', })
    self.vars = {}
  
  def teardown_method(self, method):
    pass
  
  def test_testingResults(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1104, 698)
    self.driver.find_element(By.LINK_TEXT, "View Available Polls").click()
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(3) .btn-secondary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".row").click()
    self.driver.close()
  
  def test_testingVote(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1104, 698)
    self.driver.find_element(By.LINK_TEXT, "View Available Polls").click()
    self.driver.find_element(By.LINK_TEXT, "Vote Now").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-check:nth-child(2) > label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
    self.driver.find_element(By.LINK_TEXT, "Vote again?").click()
    self.driver.find_element(By.ID, "choice2").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
    self.driver.find_element(By.CSS_SELECTOR, ".row").click()
    self.driver.close()


if __name__ == '__main__':
  unittest.main()